### ISSUE TITLE
Cacadores scouting promotions

### ISSUE THREAD

**Issue by pineappledan** [adaneslavo/More-Unique-Components-for-VP#114] opened 2018-02-16 02:48 UTC
Cacadores is supposed to get 1 random promotion from the scouting line every time it gains a level. This is not currently working

**Comment by pineappledan** [comment] 2018-02-22 03:10
I was just looking at the lua for cacadores. 

It seems overly complicated. Is there a reason to separate survivalism and trailblazer promos into separate tables if they are going to be called all at once?

**Comment by theazuresoul** [comment] 2018-02-22 05:15
This is so the function can randomly select one of the promotion lines to grant. If Survivalism is selected, it will go through the Survivalism table and pick the first one that the unit doesn't already have, and if the unit has all of them, it falls through to Trailblazer. If Trailblazer is selected, it'll go through the Trailblazer table first.

**Comment by pineappledan** [comment] 2018-02-26 04:08
I attempted a new version of the lua code. It isn't working either though :(

**Comment by pineappledan** [comment] 2018-02-27 22:54
Still not working, according to Hinin

**Comment by Infixo** [comment] 2018-03-02 15:24
I could fix this if you describe exactly how this feature is supposed to work.

**Comment by pineappledan** [comment] 2018-03-02 16:32
"Whenever this unit levels up, it gets a promotion from either the Survivalism or Trailblazer lines along with its normal promotion"

**Comment by adaneslavo** [comment] 2018-03-02 17:03
Randomly choosen between Survivalism/Trailblaizer?

**Comment by pineappledan** [comment] 2018-03-02 17:29
Unit levels up, you choose promotion
Random number between 1-2
If 1, unit receives lowest level trailblazer promotion it doesn’t already have
If 2, unit receives lowest level survivalism promotion it doesn’t already have
If unit has level 3 of one promotion line, it only gives promotions from the other promotion line
If unit has all 7 trailblazer/survivalism promotions (which should occur at level 7) then nothing happens

**Comment by Infixo** [comment] 2018-03-02 20:06
I see more changes in the code. Seems even more complicated.
I suppose that this feature is „name based”, i.e. it will only work for promos with specific names. Or is there any other way to designate a set of promotions to use?
Because the code should be:
1. Get promotions available to use.
1a. Iterate through the set and select those that player doesn’t have and has a prerequisite if one exists.
2. Select randomly a promotion.
Simple, right? And can work for any set of promotions, even if somebody messes up with recon promos.

**Comment by pineappledan** [comment] 2018-03-02 20:39
I have commented out Blue Ghost's version of this feature below my attempt (which is the one you fixed previously)

Blue Ghost's version does something similar to what you are describing.

**Comment by Infixo** [comment] 2018-03-04 15:00
Updated. Gives a random promo from a predefined set.

**Comment by adaneslavo** [comment] 2018-04-18 17:52
So anyone tested this? Can we close this issue "once and for all" :P.

**Comment by Infixo** [comment] 2018-04-18 21:02
Idk, it was re-opened without any explanation.

**Comment by pineappledan** [comment] 2018-04-18 22:14
Hinin reported that Cacadores was not working when he tested it. He doesn't post his own bugs so I was just doing it for him. I didn't corroborate his bug

**Comment by Infixo** [comment] 2018-04-19 01:04
"Doesn't working" doesn't say anything. Details, pls.

**Comment by pineappledan** [comment] 2018-04-20 06:25
Not much to say. I just tried it myself and can confirm that the cacadores is not getting a free scouting promotion when it get a level or chooses a promotion.
[Lua.log](https://github.com/adaneslavo/More-Unique-Components-for-VP/files/1930959/Lua.log)

**Comment by Infixo** [comment] 2018-04-20 09:07
[762856.937] Runtime Error: Assets\DLC\Expansion2\UI\InGame\InGame.lua:1262: attempt to index local 'addinFile' (a nil value)
[762856.937] Runtime Error: Error loading Assets\DLC\Expansion2\UI\InGame\InGame.lua.

Plus a ton of errors from EUI that should not be there.

**Comment by Infixo** [comment] 2018-04-20 16:26
The problem is that Cacador receives a promotion that is not intended for it. Only UNITCOMBAT_RECON are eligible for recon promos.
I used CanPromote because it checks for prereq promos but unfortunately it also checks if it is eligible for a given unit combat. In this case it is not, thus all recon promos are deemed invalid and none is granted.

**Comment by Infixo** [comment] 2018-04-20 17:04
![20180420185243_1](https://user-images.githubusercontent.com/25866684/39064137-a6fcab96-44cd-11e8-863c-b70c3664bc09.jpg)

![20180420185630_1](https://user-images.githubusercontent.com/25866684/39064140-aa4e5754-44cd-11e8-9764-8c1b81716966.jpg)

**Closed** 2018-04-21 07:31 UTC
Labels: fixed in new version
